FROM python:3.11-slim


RUN apt-get update && apt-get install -y \
    bash \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /app/logs

WORKDIR /app

COPY parse_db_connections.py /app/parse_db_connections.py

RUN pip install clickhouse-driver

CMD ["python", "/app/parse_db_connections.py"]
